### ISSUE TITLE
SEO enhancement issues

### ISSUE THREAD

**Issue by retore404** [retore404/PhotoSoushi#160]
SEO改善の親Issue

- [x] #159 meta descriptionの追加
- [x] #13 脱All in One SEO
- [x] #236 Tap targets are not sized appropriately 対応（タグクラウド）
- [x] #238 Tap targets are not sized appropriately 対応（ページネーション）
- [x] #239 Tap targets are not sized appropriately 対応（月別アーカイブ）
- [x] #240 Tap targets are not sized appropriately 対応（記事アーカイブウィジェット）
